name: Storm Alert Bot

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes
  workflow_dispatch:

jobs:
  storm-alerts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run alert checker
        run: python alert_bot.py

      - name: Send notification (if alert found)
        if: env.ALERT_MESSAGE != ''
        uses: notify-events/github-action@v1
        with:
          token: ${{ secrets.NOTIFY_EVENTS_TOKEN }}
          message: "${{ env.ALERT_MESSAGE }}"
